apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ignite.fullname" . }}-configmap-jmx
data:
  config.yaml: |
    ---
    startDelaySeconds: 0
    ssl: false
    lowercaseOutputName: false
    lowercaseOutputLabelNames: false
    whitelistObjectNames:
    # - "java.lang_*"
    # - "org.apache:*"
    - "org.apache:group=Kernal,*"
    - "org.apache:group=DataRegionMetrics,*"
    rules:
    - pattern: "org.apache<clsLdr=(.+), group=(.+), name=(.+)><>(.+):"
      name: "ignite_$3_$4"
      labels:
        group: "$2"
        bean: "$3"