apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ignite.fullname" . }}-configmap-jmx
data:
  config.yaml: |
    ---
    startDelaySeconds: 0
    ssl: false
    lowercaseOutputName: false
    lowercaseOutputLabelNames: false
